// Definições detalhadas dos 4 planos VIP do servidor Éden:
// 1. Cobre
// 2. Ferro
// 3. Diamante
// 4. Rubi

export const VIP_TIERS = [
  {
    id: 'cobre',
    name: 'VIP Cobre',
    tierName: 'Cobre',
    color: '#d97706',
    gradient: 'linear-gradient(135deg, #b45309, #d97706, #f59e0b)',
    bg: 'rgba(217, 119, 6, 0.12)',
    border: 'rgba(217, 119, 6, 0.45)',
    glow: 'rgba(217, 119, 6, 0.35)',
    priceVP: 250,
    priceBRL: '15,00',
    duration: '30 dias',
    tag: '[COBRE]',
    highlight: false,
    perks: [
      'Tag [COBRE] exclusiva no chat e Discord',
      'Prioridade na fila de entrada do servidor',
      '+2 Casas (/sethome adicionais)',
      'Kit Cobre diário (Poções e recursos básicos)',
      'Slot reservado em eventos da comunidade',
    ],
  },
  {
    id: 'ferro',
    name: 'VIP Ferro',
    tierName: 'Ferro',
    color: '#cbd5e1',
    gradient: 'linear-gradient(135deg, #64748b, #94a3b8, #e2e8f0)',
    bg: 'rgba(203, 213, 225, 0.12)',
    border: 'rgba(203, 213, 225, 0.45)',
    glow: 'rgba(203, 213, 225, 0.35)',
    priceVP: 500,
    priceBRL: '29,90',
    duration: '30 dias',
    tag: '[FERRO]',
    highlight: false,
    perks: [
      'Tag [FERRO] prateada no chat e tablist',
      'Todas as vantagens do VIP Cobre',
      '+4 Casas (/sethome adicionais)',
      'Comandos /hat e /craft portátil liberados',
      'Kit Ferro semanal reforçado',
      '+10% de bônus em experiência (XP)',
    ],
  },
  {
    id: 'diamante',
    name: 'VIP Diamante',
    tierName: 'Diamante',
    color: '#00f5d4',
    gradient: 'linear-gradient(135deg, #0284c7, #06b6d4, #00f5d4)',
    bg: 'rgba(0, 245, 212, 0.12)',
    border: 'rgba(0, 245, 212, 0.5)',
    glow: 'rgba(0, 245, 212, 0.45)',
    priceVP: 1000,
    priceBRL: '54,90',
    duration: '30 dias',
    tag: '[DIAMANTE]',
    highlight: true,
    badgeText: 'Mais Popular',
    perks: [
      'Tag [DIAMANTE] ciano com efeito brilhante',
      'Todas as vantagens dos planos anteriores',
      '+8 Casas (/sethome adicionais)',
      'Acesso aos comandos /enderchest e /feed',
      'Voar (/fly) livre nas vilas e lobbies',
      'Kit Diamante épico com armas encantadas',
      '+25% de bônus de XP e recompensas',
      'Partículas e cosméticos cosméticos exclusivos',
    ],
  },
  {
    id: 'rubi',
    name: 'VIP Rubi',
    tierName: 'Rubi',
    color: '#f43f5e',
    gradient: 'linear-gradient(135deg, #be123c, #e11d48, #f43f5e)',
    bg: 'rgba(244, 63, 94, 0.14)',
    border: 'rgba(244, 63, 94, 0.55)',
    glow: 'rgba(244, 63, 94, 0.5)',
    priceVP: 1800,
    priceBRL: '89,90',
    duration: '30 dias',
    tag: '[RUBI]',
    highlight: false,
    badgeText: 'Lendário',
    perks: [
      'Tag [RUBI] lendária com efeito de fogo',
      'Acesso irrestrito e total a todas as vantagens',
      'Casas (/sethome) infinitas',
      'Voar (/fly) em todas as áreas do mundo',
      'Kit Rubi Supremo com equipamentos míticos',
      'Acesso antecipado a expansões e eventos RP',
      '+50% de bônus em XP e recompensas',
      'Todas as montarias lendárias e pets raros',
      'Canal de voz VIP e suporte prioritário 24/7',
    ],
  },
];

export function getVipTier(id) {
  return VIP_TIERS.find((v) => v.id === id) || VIP_TIERS[0];
}
